user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

library:
    resource: "@LibraryBundle/Controller/"
    type:     annotation
    prefix:   /api

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix: /api


almogbaku_oauth_server_auth_login:
    path:  /api/oauth/v2/auth_login
    defaults: { _controller: FOSUserBundle:Security:login }

almogbaku_oauth_server_auth_login_check:
    path:  /api/oauth/v2/auth_login_check
    defaults: { _controller: FOSUserBundle:Security:check }


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"